package com.example.letsconnect


const val KEY_COLLECTION_USERS = "users"
const val KEY_USER_NAME = "username"
const val KEY_EMAIL = "email"
const val KEY_BIO = "bio"
const val KEY_PROFILE_IMAGE = "profileImage"
const val KEY_PASSWORD = "password"
const val KEY_PREFERENCE_NAME = "chatAppPreference"
const val KEY_IS_SIGNED_IN = "isSignedIn"
const val KEY_IMAGE = "profileImage"
const val KEY_USER_ID = "userId"
const val KEY_FCM_TOKEN = "fcmToken"
const val KEY_USER = "user"
const val VIEW_TYPE_SENT = 1
const val VIEW_TYPE_RECEIVED = 2
const val KEY_COLLECTION_CHAT = "chat"
const val KEY_SENDER_ID = "senderId"
const val KEY_RECEIVER_ID = "receiverId"
const val KEY_MESSAGE = "message"
const val KEY_TIMESTAMP = "timestamp"
const val KEY_ALL_POSTS = "allPosts"
const val KEY_TOTAL_VIEWS = "totalViews"
const val KEY_TOTAL_LIKES = "totalLikes"
const val KEY_TOTAL_COMMENTS = "totalComments"
const val KEY_POST_MESSAGE = "postMessage"
const val KEY_UPLOAD_TIME = "uploadTime"
const val KEY_FOLLOWERS = "followers"
const val KEY_FOLLOWING = "following"